---
title: "Crime Exploratory Data Analysis"
author: "Erin Franke"
date: "2022-10-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Loading 

```{r}
# Libraries 
library(tidyverse)
library(NatParksPalettes)
library(PrettyCols)
library(ggmap)
library(sf)
library(viridis)

load('Data/tractData/cleaned/gent_clean.RData')

#Minneapolis
load('Data/CrimeCleaned/tract_aggregated_minneapolis.RData')
load('Data/CrimeCleaned/tract_points_minneapolis.RData')

#Saint Paul
load('Data/CrimeCleaned/tract_aggregated_sp.RData')
load("Data/CrimeCleaned/tract_points_sp.RData")
```

Add in yearly population approximates

```{r}
tract_aggregated <- tract_aggregated %>%
  group_by(tractmod) %>%
  mutate(yearly_dif = (population_2020 - population_2010)/10,
         year = as.numeric(year),
         pop_apprx = case_when(year %in% 2010:2019 ~ population_2010 + yearly_dif*(year-2010), 
                               TRUE ~ population_2020),
         violent_1000_apprx = 1000*(Violent/pop_apprx), 
         theft_1000_apprx = 1000*(Theft/pop_apprx)) %>%
  ungroup()

tract_aggregated_sp <- tract_aggregated_sp %>%
  group_by(tractmod) %>%
  mutate(yearly_dif = (population_2020 - population_2010)/10,
         year = as.numeric(year),
         pop_apprx = case_when(year %in% 2010:2019 ~ population_2010 + yearly_dif*(year-2010), 
                               TRUE ~ population_2020),
         violent_1000_apprx = 1000*(Violent/pop_apprx), 
         theft_1000_apprx = 1000*(Theft/pop_apprx)) %>%
  ungroup()
```

Explore the yearly number of crimes per 1000 people by tract gentrification status in Minneapolis

```{r}
tract_aggregated %>%
  st_drop_geometry() %>%
  group_by(canGent_gentrified,year) %>%
  summarize(avg = mean(violent_1000_apprx)) %>%
  mutate(year = as.numeric(year)) %>%
  ggplot(aes(x=year, y=avg, color = canGent_gentrified))+
  geom_line()+
  geom_point()+
  theme_classic()+
  scale_x_continuous(breaks = c(2010:2022))

tract_aggregated %>%
  st_drop_geometry() %>%
  group_by(canGent_gentrified,year) %>%
  summarize(avg = mean(theft_1000_apprx)) %>%
  mutate(year = as.numeric(year)) %>%
  ggplot(aes(x=year, y=avg, color = canGent_gentrified))+
  geom_line()+
  geom_point()+
  theme_classic()+
  scale_x_continuous(breaks = c(2010:2022))
```

Explore 2020 distribution of violent crimes.

```{r}
mn2020 <- tract_aggregated %>%
  filter(year == 2020) %>%
  select(tractmod, year, violent_1000_apprx) %>%
  mutate(violent_d = case_when(violent_1000_apprx <=5 ~ "0-5",
                               violent_1000_apprx >6 & violent_1000_apprx  <=10 ~ "6-10",
                               violent_1000_apprx  >10 & violent_1000_apprx <= 15 ~ "11-15", 
                               TRUE ~ "16+"))
sp2020 <- tract_aggregated_sp %>%
  filter(year == 2020) %>%
  select(tractmod, year, violent_1000_apprx) %>%
  mutate(violent_d = case_when(violent_1000_apprx <=5 ~ "0-5",
                               violent_1000_apprx >6 & violent_1000_apprx  <=10 ~ "6-10",
                               violent_1000_apprx  >10 & violent_1000_apprx <= 15 ~ "11-15", 
                               TRUE ~ "16+"))

bind_rows(mn2020, sp2020) %>%
  mutate(violent_d = fct_relevel(violent_d, levels = c("0-5", "6-10", "11-15", "16+"))) %>%
  ggplot()+
  geom_sf(aes(fill =violent_d), override.order=TRUE)+
  theme_classic()+
  scale_fill_brewer(palette = "Blues")+
  labs(title = "Violent crimes per 1000 residents in 2020 by census tract", fill = "", y = "", x = "")+
  annotate("point", x = -93.1691, y = 44.938, colour = "black", size = 1) +
  annotate(geom = "text", x = -93.1691, y = 44.945, label = "Macalester \nCollege", size = 3, color = "black")+
  annotate("point", x = -93.1022, y = 44.955, colour = "black", size = 1) +
  annotate(geom = "text", x = -93.1022, y = 44.9525, label = "Capitol", size = 3, color = "black")+
  annotate("point", x = -93.2776, y = 44.9817, colour = "black", size = 1) +
  annotate(geom = "text", x = -93.285, y = 44.9817, label = "Target \nField", size = 3, color = "black")+
  annotate("point", x = -93.2732, y = 44.9585, colour = "black", size = 1) +
  annotate(geom = "text", x = -93.2732, y = 44.9615, label = "MIA", size = 3, color = "black")+
  theme(plot.title.position = "plot", 
        plot.title = element_text(family = "mono", size = 12), 
        axis.text = element_blank(), 
        axis.ticks = element_blank(), 
        axis.line = element_blank(), 
        legend.text = element_text(family = "mono"))
```

Explore 2020 distribution of thefts.

```{r}
mn2020 <- tract_aggregated %>%
  filter(year == 2020) %>%
  select(tractmod, year, theft_1000_apprx) %>%
  mutate(violent_d = case_when(theft_1000_apprx <=25 ~ "0-25",
                               theft_1000_apprx >26 & theft_1000_apprx  <=50 ~ "26-50",
                               theft_1000_apprx  >51 & theft_1000_apprx <= 75 ~ "51-75", 
                               TRUE ~ "76+"))
sp2020 <- tract_aggregated_sp %>%
  filter(year == 2020) %>%
  select(tractmod, year, theft_1000_apprx) %>%
  mutate(violent_d = case_when(theft_1000_apprx <=25 ~ "0-25",
                               theft_1000_apprx >25 & theft_1000_apprx  <=50 ~ "26-50",
                               theft_1000_apprx  >51 & theft_1000_apprx <= 75 ~ "51-75", 
                               TRUE ~ "76+"))

bind_rows(mn2020, sp2020) %>%
  mutate(violent_d = fct_relevel(violent_d, levels = c("0-25", "26-50", "51-65", "75+"))) %>%
  ggplot()+
  geom_sf(aes(fill =violent_d), override.order=TRUE)+
  theme_classic()+
  scale_fill_brewer(palette = "Blues")+
  labs(title = "Thefts per 1000 residents in 2020 by census tract", fill = "", y = "", x = "")+
  annotate("point", x = -93.1691, y = 44.938, colour = "white", size = 1) +
  annotate(geom = "text", x = -93.1691, y = 44.945, label = "Macalester \nCollege", size = 2, color = "white")+
  annotate("point", x = -93.1022, y = 44.955, colour = "white", size = 1) +
  annotate(geom = "text", x = -93.1022, y = 44.9525, label = "Capitol", size = 2, color = "white")+
  annotate("point", x = -93.2776, y = 44.9817, colour = "white", size = 1) +
  annotate(geom = "text", x = -93.285, y = 44.9817, label = "Target \nField", size = 2.5, color = "white")+
  annotate("point", x = -93.2732, y = 44.9585, colour = "white", size = 1) +
  annotate(geom = "text", x = -93.2732, y = 44.9615, label = "MIA", size = 2.5, color = "white")+
  theme(plot.title.position = "plot", 
        plot.title = element_text(family = "mono", size = 12), 
        axis.text = element_blank(), 
        axis.ticks = element_blank(), 
        axis.line = element_blank(), 
        legend.text = element_text(family = "mono"))
```

Look at overall trend in number of crimes per year.

```{r}
minn_annual <- tract_points %>%
  st_drop_geometry() %>%
  count(year) %>%
  mutate(city = "Minneapolis")

sp_annual <- tract_points_sp %>%
  st_drop_geometry() %>%
  count(year) %>%
  mutate(city = "Saint Paul") %>%
  filter(year != 2022)

bind_rows(minn_annual, sp_annual) %>%
  ggplot(aes(x=year, y=n, color = city))+
  geom_point()+
  geom_line()+
    scale_color_manual(values = c("navy", "goldenrod3"))+
  scale_x_continuous(breaks = c(2010, 2012, 2014, 2016, 2018, 2020, 2022))+
  theme_classic()+
  labs(x="Year", y= "Number of crimes", title = "Annual Crimes in the Twin Cities", color = "City")+
  theme(plot.title.position = "plot", 
        plot.title = element_text(family = "mono", size =12), 
        axis.title = element_text(family = "mono"), 
        legend.title = element_text(family = "mono"), 
        legend.text = element_text(family = "mono"), 
        axis.text = element_text(family = "mono"))
```

```{r}
gent_minn <- tract_aggregated %>%
  st_drop_geometry() %>%
  mutate(canGent = case_when(canGent_gentrified == "Cannot gentrify" ~ "Cannot Gentrify", 
                                  TRUE ~ "Gentrifiable")) %>%
  group_by(year, canGent) %>%
  summarize(avg_violent = mean(violent_1000_apprx), 
            avg_theft = mean(theft_1000_apprx)) %>%
  mutate(year = as.numeric(year), 
         city = "Minneapolis")

gent_sp <- tract_aggregated_sp %>%
  st_drop_geometry() %>%
  mutate(canGent = case_when(canGent_gentrified == "Cannot gentrify" ~ "Cannot Gentrify", 
                                  TRUE ~ "Gentrifiable")) %>%
  group_by(year, canGent) %>%
  summarize(avg_violent = mean(violent_1000_apprx), 
            avg_theft = mean(theft_1000_apprx)) %>%
  mutate(year = as.numeric(year), 
         city = "Saint Paul") %>%
  filter(year != 2022)

rbind(gent_minn, gent_sp) %>%
  ggplot(aes(x=year, y=avg_violent, color = as.factor(canGent)))+
  geom_point()+
  geom_line()+
  facet_wrap(~city)+
    scale_color_manual(values = c("navy", "goldenrod3"))+
  scale_x_continuous(breaks = c(2010, 2012, 2014, 2016, 2018, 2020, 2022))+
  theme_classic()+
  labs(x="Year", y="Violent crimes per 1000 residents" , title = "Annual violent crimes per 1000 residents by 2010 tract gentrification status", color = "")+
  theme(plot.title.position = "plot", 
        plot.title = element_text(family = "mono", size =11),
        axis.title = element_text(family = "mono"), 
        legend.title = element_text(family = "mono"), 
        legend.text = element_text(family = "mono"), 
        axis.text = element_text(family = "mono"), 
        strip.background = element_blank(), 
        strip.text = element_text(family = "mono", size =10, face = "bold"))

rbind(gent_minn, gent_sp) %>%
  ggplot(aes(x=year, y=avg_theft, color = as.factor(canGent)))+
  geom_point()+
  geom_line()+
  facet_wrap(~city)+
    scale_color_manual(values = c("navy", "goldenrod3"))+
  scale_x_continuous(breaks = c(2010, 2012, 2014, 2016, 2018, 2020, 2022))+
  theme_classic()+
  labs(x="Year", y="Thefts per 1000 residents" , title = "Annual thefts per 1000 residents by 2010 tract gentrification status", color = "")+
  theme(plot.title.position = "plot", 
        plot.title = element_text(family = "mono", size =11),
        axis.title = element_text(family = "mono"), 
        legend.title = element_text(family = "mono"), 
        legend.text = element_text(family = "mono"), 
        axis.text = element_text(family = "mono"), 
        strip.background = element_blank(), 
        strip.text = element_text(family = "mono", size =10, face = "bold"))
```





