---
title: "What is the impact of gentrification on crime in the Twin Cities?"
author: "Erin Franke"
date: "2022-11-01"
output: 
  pdf_document:
    number_sections: true
bibliography: Library.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction

Discuss positives and negatives of gentrification & current events. Discuss the organization of the paper.

# Literature Review

Review current literature and their results related to crime and gentrification here.

While there have been several studies involving gentrification and crime, this analysis will build on the current literature in two major ways. First, the focus of our analysis will be assessing the relationship between gentrification and crime in the Twin Cities. While *The Diversity of Gentrification* dove deeply into the history of gentrification in the Twin Cities, the impact on crime was not a focus and there does not appear to be widespread research on the topic available online. Second, our study will look to build on the overdispersed poisson regression models seen in *More Coffee, Less Crime?* by incorporating spatial modeling techniques including CAR and SAR models.

# Data and Methods

## Data Sources 

The data for our study was obtained from three major sources, the first being Tidycensus. Tidycensus is an R package that allows users to interface with a select number of the US Census Bureau’s data APIs and return tidyverse-ready data frames, optionally with simple feature geometry included [@tidycensus]. The two APIs we pulled from in this analysis were the 2010 and 2020 American Community Survey (ACS). The ACS is the premier source for detailed population and housing information and helps us understand the changes taking places across communities in the United States [@bureau_2022]. We gathered information across these years for a couple reasons. First, while there are new ACS reports generated annually, when studying areas as a small as census tracts decennial data is most accurate and contains the largest amount of information. Second, we were bounded by the availability of our response variable of crime rate. In Minneapolis, incident level crime data is publicly available dating back to 2010 and in Saint Paul dating back to mid-2014. As a result, we centered our study over the years 2010 through 2020. The relevant variables pulled from these APIs include tract population, median income, median home value, proportion of housing built in 5-10 year periods dating back to 1940, proportion of the population aged 24 to 65 with a bachelor's degree, number of residencies rented and owned, and race demographics. This information, along with each census tract's geometry, was collected for all tracts in Hennepin and Ramsey County. 

The two other major sources of data make up the crime portion of our study. Minneapolis crime data was obtained from Open Minneapolis, a site that seeks to provide increased access to public spatial geographic information systems (GIS) and non-spatial data that is regularly requested by private citizens and businesses [@openminneapolis]. Saint Paul crime data was collected from Open Information Saint Paul, which similarly provides access to public information to facilitate transparency and knowledge [@opensp]. Both cities provide incident level data for crimes recorded in the city limits, dating back to January 1, 2010 for Minneapolis and August 14, 2014 for Saint Paul. Relevant information collected includes crime date and time and incident type. For Minneapolis, an approximate latitude and longitude are given. For Saint Paul, an approximate address or intersection is given.

## Data Cleaning

The process to get the data in the proper format to evaluate the relationship between gentrification and crime in the Twin Cities is fairly intensive. The first of these steps is to account for redistricting. In 2010, Hennepin and Ramsey County together contained 436 census tracts. In 2020, the same area of land contained 472, as several single tracts in 2010 split into either two or three by 2020. For example, what was once census tract 38.00 in Minneapolis in 2010 became 38.01 and 38.02 in in 2020. Tract splitting typically occurs when the population within has increased beyond a key threshold and is done as population changes within an area impact decision including distribution of federal funding, the redistricting of legislative districts, business investments, and community planning among others [@detroit_2021]. This happens in 9 total instances in the Minneapolis-Saint Paul city limits, with 6 being in Minneapolis and 3 in Saint Paul. Additionally, due to a declining population in the area, there was one case in Minneapolis in which two tracts in 2010 (1023.00 and 1029.00) became a single tract in 2020 (1263.00). In order to fairly include these tracts in our analysis, we decided to aggregate tract demographic and crime information to the largest area. For tracts that split in two, this meant aggregating all crimes to the original 2010 tract borders across all years of the study as well as taking a sum or weighted mean using 2020 population for tract demographic information of interest. In the special case of tract 1263.00, the process was very similar, just this time aggregating all crimes to the 2020 tract borders across all years of the study and taking a sum or weighted mean using 2010 population for tract demographic information of interest. After this process, we ended up with 221 tracts in the Minneapolis-Saint Paul city limits with 129 in Minneapolis and 92 in Saint Paul. 

The second major step of my data cleaning process was annual crime aggregation to the census tract level. For Minneapolis, given that an approximate latitude and longitude for each crime was recorded, this process was fairly simple using R's sf package [@sfpackage]. Unfortunately, the same cannot be said for Saint Paul. Latitude and longitude of each incident were not recorded and instead we were given either an intersection such as *GRAND AV & OXFORD* or an approximate address such as *56X SNELLING AV N*. To get the approximate latitude and longitude coordinates for the intersections (which make up roughly 15.6% of the incidents) we were assisted by 2022 Macalester graduate Claire McHenry, who passed them through a geocoder in ArcGisPro. Unfortunately, ArcGIS needed both streets to have the proper identifier (e.g. AVE, RD, BLVD), while the data only listed it for the first in the pairing. Using string manipulation techniques we were able join the most likely identifier to the second street, however in instances certain streets change identifiers depending on location. For example, the data includes incidents occurring on both Battlecreek Pl and Battlecreek Rd, and there is no reasonable way to know which is the proper identifier without manually investigating each scenario. As a result of instances like this, ArcGIS was not successfully able to capture a latitude and longitude for all intersections, however the success rate was about 90.6%. 

After getting approximate coordinates for the intersections we had to complete a geocoding process for the addresses, which make up 84.4% of the data. Our first step for this process was to replace the *X* in the approximate address with a 0. We then ran the addresses through the `geocode()` function of the tidygeocoder package in R [@tidygeo]. This process took about 10 hours to run and after completion about 87.7% of the incidents had recorded coordinates. There were a couple major reasons why over 12% of the data did not receive a latitude and longitude. The first of these was that any multiple word street name was written as a single word (e.g. CESAR CHAVEZ and CESARCHAVEZ), which the geocoder could not pick up on. Using our best judgement, we split street names of unidentified crimes into multiple words. Another issue we ran into was again with identifiers. For unknown reasons, in certain instances boulevard was recorded as BD instead of BLVD in the data, and parkway was recorded in three different ways (e.g. LEXINGTON PA, LEXINGTON PK, and LEXINGTON PKWY) across the data. We converted all BDs to BLVD and all parkways to PKWY. A final change we made was with numbered streets, whose recorded addresses typically follow a structure similar to XX 10 ST W. Instead of replacing the XXs with 0s, here we chose a random number from 10 to 90 rounded to the nearest ten. Following these manual changes we were able to have an approximate latitude and longitude for 95.1% of the addresses and 94.4% of the data when we include the intersections. These data were then aggregated annually to the census tract level. However, between at times taking the most likely street identifier and in many instances approximating a random address, it it important to understand the coordinates recorded may be inaccurate even on the census tract level. Additionally, certain tracts may be underrepresented in their crime counts simply because we could not geocode any incidents of a particular street name.

## Study Design 

Having cleaned the data, the first step in understanding the relationship between gentrification and crime in the Twin Cities is to define first what makes a census tract have the *ability to gentrify* and second how we will indicate that it *has gentrified*. There are dozens of different ways to define what makes a census tract gentrifiable and gentrified, and depending on the definition used we can see drastically different results. As a result, in order to define what makes a tract have the ability to gentrify we decided to rely heavily on the methods defined in the Twin Cities specific paper *The Diversity of Gentrification* given their study's location and the fact that they took into account multiple definitions in forming their own. To identify gentrifiable tracts, Goetz et al. took the definitions of three researchers and claimed if a tract met the requirements of at least two of three, it was gentrifiable. These researchers, whose work on gentrification is widely known by scholars and activists, include Professor Lance Freeman (2005) of Columbia University, Professor Lisa Bates (2013) of Portland State University, and Lei Ding et al. (2016) of the Federal Reserve Bank of Philadelphia [@goetz_lewis_damiano_calhoun_2019]. Their methodologies are shown in the diagram below.

Of the 221 tracts, 80 were deemed not gentrifiable by all three definitions and 30 by one definition for a total of 110 (just under 50%) tracts that do not have the opportunity to undergo gentrification. Professor Freeman denoted the fewest tracts as gentrifiable at 97, followed by Professor Bates at 99 and Ding et al. at 111. The three researchers agreed completely on 55 tracts having the ability to gentrify, and in total 111 were marked as gentrifiable. The proportion of gentrifiable tracts is essentially equivalent in Minneapolis and Saint Paul, with 50.4% have the ability to gentrify in Minneapolis and 50% in Saint Paul.

Our second step was to define how we would indicate that a census tract has undergone gentrification. We again followed the methods used by Goetz et al., who continued with the definitions of Professor Lance Freeman, Professor Lisa Bates, and Lei Ding et. al. Unfortunately, Professor Lisa Bates' definition was far to complex for the data we had available. To replace this definition we looked to the report *Philadelphia's Changing Neighborhoods* from the PEW Charitable Trusts, a non-profit, non-governmental organization [@dowdall_2016]. If a tract met at least two of three definitions below, we denoted the census tract to have gentrified.

Of the 111 tracts with the opportunity to gentrify, our methodology denotes 17 as having gentrified from 2010 to 2020. Interestingly, 14 of these occurred in Minneapolis while only 3 occurred in Saint Paul, making the gentrification rates 21.5% and 6.5% of gentrifiable census tracts in Minneapolis and Saint Paul, respectively. When we break gentrification status up by each individual researcher, Ding et al. classified the largest number of tracts to have gentrified at 34, followed by the PEW Charitable Trust at 19 and Professor Lance Freeman at 16. A map is shown below of the gentrification status of the 221 tracts in the Minneapolis-Saint Paul city limits.

## Exploratory Data Analysis

Annual crime rates in Minneapolis and Saint Paul were relatively constant up until 2019 and beginning of the COVID-19 pandemic when we saw increases in both cities. As displayed in the graph below, Minneapolis has averaged just over 20,000 recorded annual incidents per year dating back 2010, while Saint Paul has averaged just under 10,000. 

It is beneficial to understand crime patterns within each city. The goal of the spaghetti plot below is to show the variance in the number of annually recorded crimes by census tract as well as show how particular tracts have seen large increases and decreases in crime rates year-to-year. We see that the majority of Minneapolis census tracts average below 400 annual crimes with a large number of tracts being between 100-200. In Saint Paul, this number is lower with the majority of tracts being under 300 annual crimes and a high concentration of them between 50-100. To effectively show the variance of annual crime across census tracts, this figure removes two Minneapolis census tracts with exceedingly high rates - 1044.00 and 1261.00 (composed of 1261.01 and 1261.02), both of which average well over 1000 annual crimes. They are located in the heart of Minneapolis, bordering the southern side of the Mississippi River.

Speaking of location, higher crime areas tend to be located near the heart of both cities, with crime rates decreasing moving outward toward the suburbs.

## Methodology

# Results

# References



